### ISSUE TITLE
I am having problem with smtp

### ISSUE THREAD

**Issue by PiyushYadav007** [mahtab2003/MOFHY-Lite#28] opened 2021-11-16 03:04 UTC
Bro I am using yandex but I am unable to use it on mofhy can anyone help me.

**Comment by jaikt** [comment] 2021-11-16 06:34
Hi, `@WhiteHacker993`! Can you share the error you are facing? 
- Did you verify your credentials? Sometimes the password or the API key changes itself 😖.
- Make sure to enable <b>Display PHP Errors</b> 
- Or add the following code in any email function e.g `function/signup.php` just after the following line `include __DIR__.'/../handler/EmailHandler.php';`. CODE - `print_r($mail);
exit;`. 
Now the function should print the email content and display errors if found.

**Comment by Lebyy** [comment] 2021-11-16 07:12
^^ and make sure you are using port `587`

**Comment by PiyushYadav007** [comment] 2021-11-16 07:19
> Hi, `@WhiteHacker993`! Can you share the error you are facing?
> 
> * Did you verify your credentials? Sometimes the password or the API key changes itself confounded.
> * Make sure to enable Display PHP Errors
> * Or add the following code in any email function e.g `function/signup.php` just after the following line `include __DIR__.'/../handler/EmailHandler.php';`. CODE - `print_r($mail); exit;`.
>   Now the function should print the email content and display errors if found.

Ok I will try

**Comment by PiyushYadav007** [comment] 2021-11-16 07:20
> ^^ and make sure you are using port `587`

Bro yandex SMTP Port is 465

**Comment by PiyushYadav007** [comment] 2021-11-16 07:28
Or I think I should try another SMTP service  with maximum number of emails I can sent using SMTP in one day

**Comment by jaikt** [comment] 2021-11-16 08:14
Yup

**Comment by Lebyy** [comment] 2021-11-16 08:58
> > ^^ and make sure you are using port `587`
> 
> Bro yandex SMTP Port is 465

Ik but for some weird reason it doesn't work on 465 and does on 587, it's the same case for #6

**Comment by PiyushYadav007** [comment] 2021-11-16 09:09
Ok I will try

> > > ^^ and make sure you are using port `587`
> > 
> > 
> > Bro yandex SMTP Port is 465
> 
> Ik but for some weird reason it doesn't work on 465 and does on 587, it's the same case for #6

Ok I will try and one more thing I should use app password or real email password?

**Comment by Lebyy** [comment] 2021-11-16 09:15
> Ok I will try
> 
> > > > ^^ and make sure you are using port `587`
> > > 
> > > 
> > > Bro yandex SMTP Port is 465
> > 
> > 
> > Ik but for some weird reason it doesn't work on 465 and does on 587, it's the same case for #6
> 
> Ok I will try and one more thing I should use app password or real email password?

The password which you used to create the email user.

**Comment by PiyushYadav007** [comment] 2021-11-16 09:15
Is there any website for checking SMTP working because in a app I am getting problem while checking
![Screenshot_2021-11-16-14-43-59-812_com dcs96 smtp_tester](https://user-images.githubusercontent.com/93871548/141956877-abe6f738-68d7-422f-974a-5da85e7c5236.jpg)
![Screenshot_2021-11-16-14-44-08-517_com dcs96 smtp_tester](https://user-images.githubusercontent.com/93871548/141956893-f9910232-ac1a-4b0c-bc52-835a9359bb29.jpg)

**Comment by PiyushYadav007** [comment] 2021-11-16 09:17
> > Ok I will try
> > > > > ^^ and make sure you are using port `587`
> > > > 
> > > > 
> > > > Bro yandex SMTP Port is 465
> > > 
> > > 
> > > Ik but for some weird reason it doesn't work on 465 and does on 587, it's the same case for #6
> > 
> > 
> > Ok I will try and one more thing I should use app password or real email password?
> 
> The password which you used to create the email user.

But again I am getting problem

**Comment by PiyushYadav007** [comment] 2021-11-16 09:31
I am getting email sent successfully but email is not coming

**Comment by PiyushYadav007** [comment] 2021-11-16 09:32
Currently I am not using SSL certificate

**Comment by Lebyy** [comment] 2021-11-16 09:51
Is your email activated? You need to login into that email from
mail.yandex.com and activate it.

**Comment by PiyushYadav007** [comment] 2021-11-16 09:57
> Is your email activated? You need to login into that email from mail.yandex.com and activate it.

Bro it is active

**Comment by jaikt** [comment] 2021-11-16 10:32
Did you configure the send as email first of all?

**Comment by WhiteHacker993** [comment] 2021-11-16 11:12
> Is your email activated? You need to login into that email from mail.yandex.com and activate it.

It is active

**Comment by PiyushYadav007** [comment] 2021-11-16 11:13
> Did you configure the send as email first of all?

How to do that?

**Comment by PiyushYadav007** [comment] 2021-11-18 02:44
Even with the correct SMTP information mail is not sending

**Comment by jaikt** [comment] 2021-11-18 03:20
I too faced the problem! Sendinblue, Maijet, Senclean didn't work in my case. So I moved my gsuite account's SMTP server. This is not a MOFHY issue. It's some sort of compatibility issue with PHPMailer (in this case we have an old version with MOFHY).

**Comment by PiyushYadav007** [comment] 2021-11-18 03:45
I have two domains on both I am using mofhy but one is working correctly and another one is not even with the same SMTP settings

**Comment by greenreader9** [comment] 2021-11-18 13:37
I have used Yandex before, and it look me almost 2 months to get email to not go to spam. I recommend using a different provider.

**Comment by PiyushYadav007** [comment] 2021-11-18 15:55
Ok but I am saying that I have 2 domains. One the first one it is working but on second one is not with same SMTP settings

**Comment by greenreader9** [comment] 2021-11-18 19:54
Again, this problem with the provider and your setup, not the script. Ask your email provider for help.

**Comment by PiyushYadav007** [comment] 2021-11-20 03:51
Hey guys look I found something when I tried to send email using this script my mail goes directly into mail folder not in spam but with mofhy it is going in spam I am not saying that it is mofhy's problem but jut have a look at this and think can we use this in mofhy.

**Comment by PiyushYadav007** [comment] 2021-11-20 03:52
<!DOCTYPE html>
<html>
  
<head>
  <title>Send Mail</title>
  <script src=
    "https://smtpjs.com/v3/smtp.js">
  </script>
  
  <script type="text/javascript">
    function sendEmail() {
      Email.send({
        Host: "smtp.gmail.com",
        Username: "example@gmail.com",
        Password: "password",
        Port: 587,
        To: ' songsd269@gmail.com',
        From: "example@gmail.com",
        Subject: "Sending Email using javascript",
        Body: "Well that was easy!!",
      })
        .then(function (message) {
          alert("mail sent successfully")
        });
    }
  </script>
</head>
  
<body>
  <form method="post">
    <input type="button" value="Send Email" 
        onclick="sendEmail()" />
  </form>
</body>
  
</html>

**Comment by PiyushYadav007** [comment] 2021-11-20 03:53
[New.zip](https://github.com/mahtab2003/MOFHY-Lite/files/7573873/New.zip)

**Comment by mahtab2003** [comment] 2021-11-20 04:33
Well because in mofhy From parameter is used the mail goes to spam box it can be fixed by generating gpg encryption key in cpanel

**Comment by PiyushYadav007** [comment] 2021-11-20 04:44
How to do that?

**Comment by mahtab2003** [comment] 2021-11-20 08:27
In emailhanlder.php file remove $mail->From parameter and its value

**Comment by zeroninefourfour** [comment] 2021-11-23 11:49
yandex smtp port is 587.
<img width="492" alt="截圖 2021-11-23 下午7 49 14" src="https://user-images.githubusercontent.com/69704016/143019063-30946428-2c34-485b-ac46-0deb8170acbb.png">
.

**Comment by mahtab2003** [comment] 2021-12-06 08:28
If the issue is solved please close this issue

**Closed as completed by mahtab2003** 2021-12-06 08:28 UTC
